# Generated by Django 2.2 on 2022-05-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_perfil_contatos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
    ]
